all:
	clear
	
# algoritmos de menor caminho
astar:
	python aula_08/menor_caminho/astar_algorithm.py


# algoritmos de busca local
hillclimb:
	python aula_09/busca_local/random_hillclimb.py

stochastic:
	python aula_09/busca_local/stochastic_hillclimb.py


annealing:
	python aula_09/busca_local/annealing_hillclimb.py

# algoritmos... ?
genetic:
	python genetic_algorithm.py